---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: flux
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: flux
    spec:
      # The serviceAccount is only needed for Kubernetes with RBAC
      # serviceAccount: flux
      volumes:
      - name: git-key
        secret:
          secretName: flux-git-deploy
      - name: flux-registry-auth
        secret:
          secretName: flux-registry-auth
      containers:
      - name: flux
        image: quay.io/weaveworks/flux:master-2cd55ca
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3030 # informational
        volumeMounts:
        - name: git-key
          mountPath: /etc/fluxd/ssh
        - name: flux-registry-auth
          mountPath: /etc/fluxd/docker
        args:
        - --docker-config=/etc/fluxd/docker/gke-deploy-docker-config.json
        # replace (at least) the following URL
        - --git-url=git@github.com:gke-deploy-demo/cowsay-config
        - --git-branch=master
        # include these to connect to an "upstream" service (e.g.,
        # Weave Cloud). The token is particular to the service.
        - --connect=wss://cloud.weave.works/api/flux
        - --token=<weave-cloud-token>
        - --git-poll-interval=10s
        - --registry-poll-interval=10s
