---
apiVersion: v1
kind: Service
metadata:
  name: cowsay-server
  labels:
    name: cowsay-server
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30001
  selector:
    name: cowsay-server
